# Site settings
title: "Sof Kapa Photography"
tagline: "Cinematic Lifestyle Photography in Melbourne"
description: "Melbourne lifestyle photographer specialising in portraits, food, and travel. Cinematic photography for families, newborns, maternity, small weddings, food, drinks, artisans, events, and travel."
url: "https://sofkapaphotography.com"   # your live domain
baseurl: ""                             # leave blank if site is served from root
image: assets/social_sharing/new_social-banner_2025.jpg

# Author info
author:
  name: "Sof Kapa"
  url: "https://sofkapaphotography.com"

# SEO and social
seo:
  image: "/assets/social_sharing/new_social-banner_2025.jpg"
  image_alt: "Sof Kapa Photography Banner"


twitter:
  twitter_image: "assets/social_sharing/new_social-banner_2025.jpg"
  card: summary_large_image

facebook:
  publisher: "https://www.facebook.com/sofkapaphoto"   # update with your FB page
  app_id:    ""   # optional if you own a Facebook App

social:
  name: "Sof Kapa Photography"
  links:
    - https://www.instagram.com/sofkapaphotography
    - https://www.facebook.com/sofkapaphoto
    # - https://twitter.com/sofkapaphoto   # optional


# Plugins
plugins:
  - jekyll-sitemap
  # - jekyll-seo-tag
  - jekyll-paginate-v2   # enable if you need pagination for many galleries
  - jekyll-redirect-from # enable if you ever rename URLs
  # - jekyll-assets        # enable for image optimisation


# Permalinks & output
# permalink: pretty
future: false

collections:
  posts:
    output: true
    permalink: /gallery/:slug 


# Defaults (front matter defaults)
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      seo_description_max_words: 160

# Markdown & Liquid settings
markdown: kramdown
highlighter: rouge

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - tmp/
  - _drafts/


